[package]
name = "lcov-html"
version = "0.1.0"
authors = ["Nish Tahir <nishtahir@outlook.com>"]
edition = "2018"

dirs = ["templates"]

[dependencies]
clap = { version = "3.0.0-beta.1", features = ["yaml"] }
askama = "0.9.0"